version: '2.2'

x-net: &net
  networks:
      - main

services:

  notebook:
    <<: *net
    build: .
    environment:
      - DJ_HOST=mydb
      - DJ_USER=root
      - DJ_PASS=cadwell2020
    ports:
      - "8888:8888"
    volumes:
      - ./:/notebooks
    depends_on:
      - mydb

  mydb:
    <<: *net
    image: datajoint/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=cadwell2020
    volumes:
      - ./db:/var/lib/mysql

networks:
  main:
